# Copyright Vespa.ai. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-configserver
spec:
  # Use three servers for proper ZooKeeper quorum:
  replicas: {{ .Values.configserver.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-configserver
      name: {{ .Release.Name }}-internal
  serviceName: {{ .Release.Name }}-internal
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-configserver
        name: {{ .Release.Name }}-internal
    spec:
      initContainers:
      - name: chown-var
        securityContext:
          runAsUser: 0
        image: busybox
        command: ["sh", "-c", "chown -R 1000 /opt/vespa/var"]
        volumeMounts:
          - name: vespa-var
            mountPath: /opt/vespa/var
      - name: chown-logs
        securityContext:
          runAsUser: 0
        image: busybox
        command: ["sh", "-c", "chown -R 1000 /opt/vespa/logs"]
        volumeMounts:
          - name: vespa-logs
            mountPath: /opt/vespa/logs
      containers:
      - name: vespa-configserver
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        args: ["configserver,services"]
        imagePullPolicy: Always
        securityContext:
          runAsUser: 1000
        volumeMounts:
        - name: vespa-var
          mountPath: /opt/vespa/var
        - name: vespa-logs
          mountPath: /opt/vespa/logs
        - name: vespa-workspace
          mountPath: /workspace
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-config
        # Note that the below are minimum resources for demo use.
        # Use 4G or more for real use cases
        resources:
          requests:
            memory: "3000m"
          limits:
            memory: "3000m"
  volumeClaimTemplates:
  # The below are tiny volumes for demo purposes.
  - metadata:
      name: vespa-var
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: vespa-logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: vespa-workspace
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
