# Copyright Vespa.ai. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.namespace }}
data:
  VESPA_CONFIGSERVERS: "{{ .Release.Name }}-configserver-0.zencore-vespa-internal.{{ .Values.namespace }}.svc.cluster.local,
  {{ .Release.Name }}-configserver-1.zencore-vespa-internal.{{ .Values.namespace }}.svc.cluster.local,
  {{ .Release.Name }}-configserver-2.zencore-vespa-internal.{{ .Values.namespace }}.svc.cluster.local"
  VESPA_CONFIGSERVER_JVMARGS: "-Xms1024M -Xmx1024M"
  VESPA_CONFIGPROXY_JVMARGS: "-Xms1024M -Xmx1024M"
  VESPA_CONFIG_SOURCES: "{{ .Release.Name }}-configserver-0.zencore-vespa-internal.{{ .Values.namespace }}.svc.cluster.local:19071,
  {{ .Release.Name }}-configserver-1.zencore-vespa-internal.{{ .Values.namespace }}.svc.cluster.local:19071,
  {{ .Release.Name }}-configserver-2.zencore-vespa-internal.{{ .Values.namespace }}.svc.cluster.local:19071"

# The JVMARGS settings are to minimize, for demo purposes only -
# remove for production use.
