# Copyright Vespa.ai. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-content
spec:
  replicas: {{ .Values.content.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-content
      name: {{ .Release.Name }}-internal
  serviceName: {{ .Release.Name }}-internal
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-content
        name: {{ .Release.Name }}-internal
    spec:
      initContainers:
      - name: chown-var
        securityContext:
          runAsUser: 0
        image: busybox
        command: ["sh", "-c", "chown -R 1000 /opt/vespa/var"]
        volumeMounts:
        - name: vespa-var
          mountPath: /opt/vespa/var
      containers:
      - name: vespa-content
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        args: ["services"]
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-config
        securityContext:
          runAsUser: 1000
        volumeMounts:
        - name: vespa-var
          mountPath: /opt/vespa/var
        resources:
          requests:
            memory: "1G"
          limits:
            memory: "1G"
  volumeClaimTemplates:
  - metadata:
      name: vespa-var
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
