# Copyright Vespa.ai. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-internal
  labels:
    name: {{ .Release.Name }}-internal
spec:
  selector:
    name: {{ .Release.Name }}-internal
  clusterIP: None
