apiVersion: v1
kind: Service
metadata:
  name: document-index-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-query-container
