apiVersion: v1
kind: Service
metadata:
  name: document-index-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
    - port: 19071
      targetPort: 19071
      protocol: TCP
      name: rpc
  selector:
    app: {{ .Release.Name }}-configserver
    name: {{ .Release.Name }}-internal
