apiVersion: v1
kind: Service
metadata:
  name: document-index-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8081
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 19071
      targetPort: 19071
      protocol: TCP
      name: vespa-config
  selector:
    app: {{ .Release.Name }}-query-container
